### ISSUE TITLE
缺少DaggerAppLayerComponent报错

### ISSUE THREAD

**Issue by laucherish** [Sloaix/ZhihuDailyFluxRRD#1]
DailyApp里面的
AppLayerComponent.Instance.init(DaggerAppLayerComponent.builder().build());
这行代码报错，找不到DaggerAppLayerComponent类。

**Comment by codedavid** [comment]
找不到DaggerAppLayerComponent类。

**Comment by isuudev** [comment]
在编译时，Dagger 2会自动生成以Dagger_为前缀的此接口的实现DaggerAppLayerComponent.通过调用此的builder()方法来获得一个实例，通过该方法返回的builder来设置其他依赖，通过build来获得一个新的实例。
