### ISSUE TITLE
编译不过啊

### ISSUE THREAD

**Issue by forzajuve** [Sloaix/ZhihuDailyFluxRRD#13]
Information:Gradle tasks [:app:assembleDebug]
/Users/forzajuve/Desktop/git-hub/android/ZhihuDailyFluxRRD/app/src/main/java/lsxiao/com/zhihudailyrrd/inject/module/ClientApiModule.java
Error:(23, 8) 错误: 类ClientAPIModule是公共的, 应在名为 ClientAPIModule.java 的文件中声明
/Users/forzajuve/Desktop/git-hub/android/ZhihuDailyFluxRRD/app/src/main/java/lsxiao/com/zhihudailyrrd/protocol/ClientApi.java
Error:(14, 8) 错误: 类ClientAPI是公共的, 应在名为 ClientAPI.java 的文件中声明
/Users/forzajuve/Desktop/git-hub/android/ZhihuDailyFluxRRD/app/src/main/java/lsxiao/com/zhihudailyrrd/DailyApp.java
Error:(6, 34) 错误: 程序包com.lsxiao.apollo.generate不存在
Error:(9, 49) 错误: 找不到符号
符号:   类 DaggerApplicationComponent
位置: 程序包 lsxiao.com.zhihudailyrrd.inject.component
Error:(26, 44) 错误: 找不到符号
符号:   变量 DaggerApplicationComponent
位置: 类 DailyApp
Error:(33, 27) 错误: 找不到符号
符号:   变量 SubscriberBinderImplement
位置: 类 DailyApp
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.

> Compilation failed; see the compiler error output for details.
> Information:BUILD FAILED
> Information:Total time: 1.138 secs
> Information:7 errors
> Information:0 warnings
> Information:See complete output in console

**Comment by gumqii** [comment]
ClientAPIModule和ClientAPI接口名称和java文件命名不一致，改成一致即可。
然后clear一下工程，就可以编译通过了
