### ISSUE TITLE
求教使用dragger后，如何处理下载上传监听进度

### ISSUE THREAD

**Issue by sunlimiter** [Sloaix/ZhihuDailyFluxRRD#3]
dragger okhttp Retrofit rajava 对于上传下载需要进度的监听，有什么好的思路吗

**Comment by Sloaix** [comment]
给你一个思路，这一块应该是要用到okhttp的拦截器了，我没有自己操作过，给你一篇文章看看。
http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/0904/3416.html
