### ISSUE TITLE
好复杂呀！好难看懂呀

### ISSUE THREAD

**Issue by Tanglonglong** [Sloaix/ZhihuDailyFluxRRD#4]
刚接触Rxjava和Retrofit 可能是本人懂的还不够  好难看懂框架
还有 我看到了代码里的Observable都是通过Retrofit获取到的网络数据 或缓存数据 
那我就在想了 我数据都获得了(在主线程拿到的) 我直接用就行了 为什么还要用Observable.doOnSubscribe订阅-发布一下呢?   数据如果不是UI线程拿到的 我还能理解  
还是有时间 好好研究一下 楼主有时间 还望 指点一下！

**Comment by Sloaix** [comment]
doOnSubscribe ，在订阅的时候在指定线程做一些准备的操作，比如说显示loading(需要在主线程执行)。
