### ISSUE TITLE
NewsDetailStore 是否应该是单例模式

### ISSUE THREAD

**Issue by sidcoding** [Sloaix/ZhihuDailyFluxRRD#8]
NewsDetailStore 和 NewsListStore 是否都应该是单例模式，使用目前的代码，会不断的创建新的实例

**Comment by Sloaix** [comment]
每一个Fragment对应Flux中的View,每个Store的作用是保存View的状态，所以应该是唯一的，也就是说每一个View应该对应有一个Store。

如果Fragment里面有一个Edittext，Fragment同时被实例化两次，两个Edittext有可能内容不同，你怎么用一个Store来正确的保存View状态呢。
