### ISSUE TITLE
DaggerApplicationComponent file is miss

### ISSUE THREAD

**Issue by subjason** [Sloaix/ZhihuDailyFluxRRD#9]
DaggerApplicationComponent file is miss

**Comment by Sloaix** [comment]
the “Dagger_” files which are all generated by Dagger2 when compile runtime.

maybe you can try to clean and run this project.

see this issue [点击缺少DaggerAppLayerComponent报错](https://github.com/lsxiao/ZhihuDailyFluxRRD/issues/1) .
